const jobs = [
    { id: 1, title: "Junior Front-end Developer", field: "Front-end", salary: 800, location: "Baku" },
    { id: 2, title: "Back-end Developer", field: "Back-end", salary: 1200, location: "Ganja" },
    { id: 3, title: "Data Analyst", field: "Data Science", salary: 1000, location: "Baku" },
    { id: 4, title: "ML Engineer", field: "Machine Learning", salary: 1500, location: "Remote" },
    { id: 5, title: "QA Tester", field: "QA", salary: 900, location: "Sumqayit" },
    { id: 6, title: "DevOps Intern", field: "DevOps", salary: 700, location: "Baku" },
    { id: 7, title: "UI/UX Designer", field: "UI/UX", salary: 1100, location: "Baku" },
    { id: 8, title: "Cybersecurity Analyst", field: "Cybersecurity", salary: 1300, location: "Remote" },
    { id: 9, title: "Middle Front-end Developer", field: "Front-end", salary: 1500, location: "Remote" },
    { id: 10, title: "Senior Back-end Developer", field: "Back-end", salary: 2000, location: "Baku" },
    { id: 11, title: "QA Automation Engineer", field: "QA", salary: 1300, location: "Ganja" },
    { id: 12, title: "AI Research Intern", field: "Machine Learning", salary: 900, location: "Remote" },
    { id: 13, title: "DevOps Specialist", field: "DevOps", salary: 1600, location: "Sumqayit" },
    { id: 14, title: "UI Designer", field: "UI/UX", salary: 950, location: "Baku" },
    { id: 15, title: "Cybersecurity Engineer", field: "Cybersecurity", salary: 1700, location: "Remote" },
    { id: 16, title: "Junior Data Scientist", field: "Data Science", salary: 1100, location: "Baku" },
    { id: 17, title: "Front-end Intern", field: "Front-end", salary: 500, location: "Baku" },
    { id: 18, title: "Back-end Intern", field: "Back-end", salary: 550, location: "Ganja" },
    { id: 19, title: "Machine Learning Specialist", field: "Machine Learning", salary: 1800, location: "Remote" },
    { id: 20, title: "Data Science Mentor", field: "Data Science", salary: 2000, location: "Remote" },
    { id: 21, title: "Lead QA Engineer", field: "QA", salary: 1600, location: "Sumqayit" },
    { id: 22, title: "UX Researcher", field: "UI/UX", salary: 1250, location: "Baku" },
    { id: 23, title: "DevOps Engineer", field: "DevOps", salary: 1900, location: "Baku" },
    { id: 24, title: "Cybersecurity Consultant", field: "Cybersecurity", salary: 2100, location: "Remote" },
    { id: 25, title: "React Developer", field: "Front-end", salary: 1700, location: "Remote" },
    { id: 26, title: "Node.js Developer", field: "Back-end", salary: 1600, location: "Ganja" },
    { id: 27, title: "Product Designer", field: "UI/UX", salary: 1400, location: "Remote" },
    { id: 28, title: "Senior QA Lead", field: "QA", salary: 1900, location: "Baku" },
    { id: 29, title: "AI Product Manager", field: "Machine Learning", salary: 2200, location: "Remote" },
    { id: 30, title: "Senior Data Scientist", field: "Data Science", salary: 2400, location: "Baku" }
];